Replaced byte with uint8_t in the arduino files.
AmboVent-1690-108/AmboVent pull request #43
Opened 2020-04-17 19:49 UTC by SaarYogev

Deals with the additional part of #32 (not the sub issue of #11, that'll be in a future PR).

2020-04-17 20:12 UTC, ElectricRCAircraftGuy commented
@SaarYogev, thanks. I'll see if I can look at it over the weekend, or maybe @nimrod46 can. Can you do me a favor and run the auto-formatter too? 

    ./run_clang-format.sh

Follow the instructions here: I want to make sure they are easy enough to follow for you to get it to work.

2020-04-17 20:51 UTC, SaarYogev commented
Sure, I'll try it tomorrow. By the way, is auto-formatting an issue already? If so just mention it, if not I'll open one. Also, we need to include it in CI ( #42 ).

2020-04-18 19:42 UTC, SaarYogev commented
@ElectricRCAircraftGuy `./run_clang-format.sh` produces an error:
```bash
$ ./run_clang-format.sh
THIS_DIR = "..../AmboVent"
FILE_LIST = "..../AmboVent/3-Software/Arduino/ventilation_machine/ventilation_machine.ino"
Formatting ..../AmboVent/3-Software/Arduino/ventilation_machine/ventilation_machine.ino
YAML:184:22: error: unknown key 'Delimiter'
  - Delimiter:       pb
                     ^~
Error reading ..../AmboVent/3-Software/Arduino\.clang-format: invalid argument
```
Where `....` is anything  above the project's root directory.

2020-04-18 19:44 UTC, SaarYogev commented
Is that holding this PR back? If not, it's probably better to open a separate issue on making sure `run_clang-format.sh` works.

2020-04-20 05:52 UTC, ElectricRCAircraftGuy requested changes
(Blocking) I don't want to change the core Arduino libraries unless we absolutely have to, which we don't here. 

(Not blocking the merge): Also, I see 13 missed opportunities to change `byte` casts or enum types to `uint8_t` in ventilation_machine.ino.

2020-04-20 05:52 UTC, ElectricRCAircraftGuy commented on 3-Software/Arduino/Libraries/Servo/src/avr/Servo.cpp
> +  uint8_t channel = this->servoIndex;
Let's not change anything in the core libraries. Please remove all changes to Libraries/Servo. Otherwise we make our libraries deviate from the Arduino core with no real differences, and it adds work when the core libraries change or get upgraded.

2020-04-20 05:54 UTC, ElectricRCAircraftGuy commented
@SaarYogev, 

> Is that holding this PR back? If not, it's probably better to open a separate issue on making sure `run_clang-format.sh` works.

Yes, we don't want to land any future PRs without running the clang formatter first on the core AmboVent files (this doesn't include Libraries we didn't write--we won't format those).

Please open an issue and I'd love to help you debug getting the formatter to work. The variable renames here are trivial so I'll just catch them real quick. Getting the formatter to work on anyone's system who wants to merge a PR is more important to me, however, so let's work that out if you are willing to. I want to ensure we have instructions that are easy to follow.

2020-04-20 08:01 UTC, ElectricRCAircraftGuy commented
@SaarYogev , no need to fix any of this. #46 does a ton of other stuff and also replaces this PR while I'm at it. I'd still like to get your clang-format tool working, however, so I'd be happy to help you debug if you are willing to open an issue. We need to make that process smooth, as running the formatter is a requirement to land code.

2020-04-20 08:54 UTC, ElectricRCAircraftGuy commented
> By the way, is auto-formatting an issue already? If so just mention it, if not I'll open one. Also, we need to include it in CI ( #42 ).

Agreed, we need to get the auto-formater to run in CI if possible. I don't think we have an open issue to integrate the auto-formatter with CI. Feel free to open an issue for that. I only had one to get the auto-formatter working manually I think. Yes, see #21. It's closed.

2020-04-21 08:03 UTC, closed without merging